/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as BlockedIndexRouteImport } from './routes/blocked/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedIndexRoute = BlockedIndexRouteImport.update({
  id: '/blocked/',
  path: '/blocked/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/login': typeof LoginIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/login': typeof LoginIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked/': typeof BlockedIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blocked' | '/exercises' | '/login' | '/tracking' | '/wiki'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blocked' | '/exercises' | '/login' | '/tracking' | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/blocked/'
    | '/exercises/'
    | '/login/'
    | '/tracking/'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedIndexRoute: typeof BlockedIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked/': {
      id: '/blocked/'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedIndexRoute: BlockedIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  TrackingIndexRoute: TrackingIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
