/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking/index'
import { Route as ProgramIndexRouteImport } from './routes/program/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GuidebookIndexRouteImport } from './routes/guidebook/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as BlockedIndexRouteImport } from './routes/blocked/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidebookIndexRoute = GuidebookIndexRouteImport.update({
  id: '/guidebook/',
  path: '/guidebook/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedIndexRoute = BlockedIndexRouteImport.update({
  id: '/blocked/',
  path: '/blocked/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/guidebook': typeof GuidebookIndexRoute
  '/login': typeof LoginIndexRoute
  '/program': typeof ProgramIndexRoute
  '/tracking': typeof TrackingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/guidebook': typeof GuidebookIndexRoute
  '/login': typeof LoginIndexRoute
  '/program': typeof ProgramIndexRoute
  '/tracking': typeof TrackingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked/': typeof BlockedIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/guidebook/': typeof GuidebookIndexRoute
  '/login/': typeof LoginIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/tracking/': typeof TrackingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/exercises'
    | '/guidebook'
    | '/login'
    | '/program'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/exercises'
    | '/guidebook'
    | '/login'
    | '/program'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/blocked/'
    | '/exercises/'
    | '/guidebook/'
    | '/login/'
    | '/program/'
    | '/tracking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedIndexRoute: typeof BlockedIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  GuidebookIndexRoute: typeof GuidebookIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidebook/': {
      id: '/guidebook/'
      path: '/guidebook'
      fullPath: '/guidebook'
      preLoaderRoute: typeof GuidebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked/': {
      id: '/blocked/'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedIndexRoute: BlockedIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  GuidebookIndexRoute: GuidebookIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProgramIndexRoute: ProgramIndexRoute,
  TrackingIndexRoute: TrackingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
